# Generated by Django 4.0.4 on 2022-04-27 21:06

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog_type', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('allowed_users', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='docaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=20)),
                ('doc_name', models.CharField(max_length=20)),
                ('doc_age', models.IntegerField(max_length=3)),
                ('doc_gender', models.CharField(max_length=20)),
                ('doc_nid', models.IntegerField(max_length=17)),
                ('doc_address', models.CharField(max_length=100)),
                ('doc_birth', models.DateField()),
                ('doc_mobile', models.IntegerField(max_length=11)),
                ('doc_email', models.EmailField(max_length=30)),
                ('doc_password', models.CharField(max_length=20)),
                ('doc_confirm_password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='psychiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=30)),
                ('ps_email', models.EmailField(max_length=30)),
                ('ps_mobile', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='quizresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.filepath),
        ),
    ]
