# Generated by Django 3.2.9 on 2022-02-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_accounts_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='msgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=20)),
                ('person_email', models.CharField(max_length=20)),
                ('person_contact', models.IntegerField(max_length=11)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
    ]
