# Generated by Django 3.2.9 on 2022-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220413_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog_type', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=500)),
            ],
        ),
    ]
