# Generated by Django 4.0.4 on 2022-04-25 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chat_alter_accounts_id_alter_msgs_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='docaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=20)),
                ('doc_name', models.CharField(max_length=20)),
                ('doc_age', models.IntegerField(max_length=3)),
                ('doc_gender', models.CharField(max_length=20)),
                ('doc_nid', models.IntegerField(max_length=17)),
                ('doc_type', models.CharField(max_length=20)),
                ('doc_address', models.CharField(max_length=100)),
                ('doc_birth', models.DateField()),
                ('doc_mobile', models.IntegerField(max_length=11)),
                ('doc_email', models.EmailField(max_length=30)),
                ('doc_password', models.CharField(max_length=20)),
                ('doc_confirm_password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
