# Generated by Django 4.0.4 on 2022-04-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_docaccounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docaccounts',
            name='doc_type',
        ),
    ]
