# Generated by Django 4.0.4 on 2022-04-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogs'),
        ('home', '0007_remove_docaccounts_doc_type'),
    ]

    operations = [
    ]
